# This is a basic workflow to help you get started with Actions

name: Update Dependencies

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '13 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: palewire/install-python-pipenv-pipfile@v2
        with:
        # “The version of Python to use”
          python-version: 3.8

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: pipenv update
    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch-suffix: random
          delete-branch: true
          body: Automated dependency PR
          labels: update deps
